[module]
title = "SAP Source System Asset/Equipment Metadata"

[packages]
tags = [
    "sourcesystem",
    "quickstart",
]

[dependencies]
modules = []

[[data]]
repoType = "http"
repo = "https://apps-cdn.cogniteapp.com/toolkit"
source = "publicdata/assets.Table.csv"
destination = "raw/dump.Table.csv"


[[extra_resources]]
location = "cdf_common/data_sets/demo.DataSet.yaml"

[[extra_resources]]
location = "cdf_common/data_models/demo.Space.yaml"

[[extra_resources]]
location = "cdf_common/raw/source.DataBase.yaml"

[[extra_resources]]
location = "models/cdf_process_industry_extension/data_models"
