[module]
title = "Contextualisation direct relation transformation"
is_selected_by_default = false

[packages]
tags = [
    "contextualization",
    "quickstart",
]

[dependencies]
modules = []

[[extra_resources]]
location = "cdf_common/data_sets/demo.DataSet.yaml"

[[extra_resources]]
location = "cdf_common/data_models/demo.Space.yaml"

