externalId: 'ep_ctx_timeseries_{{location_name}}_{{source_name}}_asset'
config:
  data:
    debug: False
    runAll: False
    rawdb: 'timeseries_{{location_name}}_{{source_name}}'
    rawTableGood: 'contextualization_good'
    rawTableBad: 'contextualization_bad'
    rawTableManual: 'contextualization_manual_input'
    timeSeriesPrefix: [pi_, opc-ua]
    timeSeriesDataSetExtId: 'ds_timeseries_{{location_name}}'
    assetRootExtIds: [{{external_root_id_asset}}]
    matchThreshold: 0.75
