cdf_cluster: ${CDF_CLUSTER}
cicd_clientId: ${IDP_CLIENT_ID}
cicd_clientSecret: ${IDP_CLIENT_SECRET}
cicd_tokenUri: ${IDP_TOKEN_URL}
cdfProjectName: ${CDF_PROJECT}
# Optional: If idP requires providing the scopes
cicd_scopes:
  - ${IDP_SCOPES}
# Optional: If idP requires providing the audience
cicd_audience: ${IDP_AUDIENCE}
# Seven minutes past each hour
scheduleHourly: '7 * * * *'
# Every fifteen minutes
scheduleQuarterly: '0/15 * * * *'
# Daily at 1:35 AM
scheduleDaily: '35 1 * * *'

# In the example below we are setting up a project based on the Open Industry Data (OID),
# that originates from the Valhall oil rig. Note that the location/site is NOT used
# to structure the data when on-boarding. The expectation is that a single source system
# and it's data pipeline may supply data for multiple locations/sites.
# The structuring of the data based on site/location should happen as part of processing
# the data in CDF, i.e. contextualisation.
#
# Each of data resource types have assigned the source system where the data originates from.
# This information will be used to construct RAW database names, and to create data sets in CDF,
# and can be used to control access.
default_location: oid
source_asset: workmate
source_event: workmate
source_workorder: workmate
source_files: fileshare
source_timeseries: pi
