dataset: ingestion
instanceSpace: springfield_instances
directRelationJob: ctx_files_direct_relation_write
rawSourceDatabase: ingestion
rawStateDatabase: contextualizationState
rawStateTable: diagramParsing
schemaSpace: cdf_cdm
annotationSpace: springfield_instances