[module]
title = "Ingestion Workflow"
is_selected_by_default = true

[packages]
tags = [
    "quickstart",
]

[dependencies]
modules = []

[[extra_resources]]
location = "cdf_common/data_sets/demo.DataSet.yaml"