workflow: ingestion
groupSourceId: <not set>
ingestionClientId: ${INGESTION_CLIENT_ID}
ingestionClientSecret: ${INGESTION_CLIENT_SECRET}

assetTransformationExternalId: sap_assets_springfield_s4hana
equipmentTransformationExternalId: sap_equipment_springfield_s4hana
equipmentToAssetTransformationExternalId: sap_equipment_to_asset_springfield_s4hana
timeseriesTransformationExternalId: pi_timeseries_springfield_aveva_pi
maintenanceOrderTransformationExternalId: sap_maintenance_orders_springfield_s4hana
operationTransformationExternalId: sap_operations_springfield_s4hana
operationToMaintenanceOrderTransformationExternalId: sap_operation_to_maintenance_order_springfield_s4hana
fileTransformationExternalId: files_metadata_springfield
activityToAssetTransformationExternalId: activity_to_asset
activityToEquipmentTransformationExternalId: activity_to_equipment
activityToTimeSeriesTransformationExternalId: activity_to_timeseries
timeSeriesToAssetTransformationExternalId: timeseries_to_asset
timeSeriesToEquipmentTransformationExternalId: timeseries_to_equipment
pandidContextualizationFunction: contextualization_p_and_id_annotater
contextualization_connection_writer: contextualization_connection_writer

dataset: ingestion
rawSourceDatabase: ingestion
rawStateDatabase: contextualizationState
schemaSpace: sp_enterprise_process_industry
schemaSpace2: cdf_cdm
schemaSpace3: cdf_idm

instanceSpaces:
  - springfield_instances
  - cdf_cdm_units

runWorkflowUserIds:
  - <your user id>
