icapi_extractors_source_id: <OBJECT ID FOR ICAPI EXTRACTORS ENTRA GROUP>

tokenUri: ${IDP_TOKEN_URL}
cdfProjectName: ${CDF_PROJECT}
scopes: ${IDP_SCOPES}
icapi_trigger_client_id: ${IDP_CLIENT_ID}
icapi_trigger_client_secret: ${IDP_CLIENT_SECRET}
icapi_extractors_client_id: ${ICAPI_EXTRACTORS_CLIENT_ID}
icapi_extractors_client_secret: ${ICAPI_EXTRACTORS_CLIENT_SECRET}