externalId: 'ep_ctx_3d_{{location_name}}_{{source_name}}_annotation'
config:
  data:
    debug: False
    runAll: False
    rawdb: '3d_{{location_name}}_{{source_name}}'
    rawTableGood: 'contextualization_good'
    rawTableBad: 'contextualization_bad'
    rawTableManual: 'contextualization_manual_input'
    assetRootExtId: {{external_root_id_asset}}
    3dDataSetExtId: 'ds_3d_{{location_name}}'
    3dModelName: '{{3d_model_name}}'
    matchThreshold: 0.75
    keepOldMapping: False

