environment:
  name: demo
  project: project-loader-dev
  type: dev
  # This should be a used to specify which modules and packages to deploy locally and in the GitHub Action.
  # You can have multiple deploy commands.
  # Order is important.
  selected:
    - cdf_auth_readwrite_all

variables:
  modules:
    # Globally defined variables are available to all submodules
      # of the cognite_modules.
    cdf_cluster: ${CDF_CLUSTER}
    cicd_clientId: ${IDP_CLIENT_ID}
    cicd_clientSecret: ${IDP_CLIENT_SECRET}
    cicd_tokenUri: ${IDP_TOKEN_URL}
    cdfProjectName: ${CDF_PROJECT}
    # Optional: If idP requires providing the scopes
    cicd_scopes:
    - ${IDP_SCOPES}
    # Optional: If idP requires providing the audience
    cicd_audience: ${IDP_AUDIENCE}
    # Seven minutes past each hour
    scheduleHourly: 7 * * * *
    # Every fifteen minutes
    scheduleQuarterly: 0/15 * * * *
    # Daily at 1:35 AM
    scheduleDaily: 35 1 * * *


    dataset: ingestion
    instanceSpace: springfield_instances
    rawSourceDatabase: ingestion
    rawStateDatabase: contextualizationState
    schemaSpace: cdf_cdm
    annotationSpace: springfield_instances
    assetTransformationExternalId: sap_assets_springfield_s4hana
    equipmentTransformationExternalId: sap_equipment_springfield_s4hana
    equipmentToAssetTransformationExternalId: sap_equipment_to_asset_springfield_s4hana
    timeseriesTransformationExternalId: pi_timeseries_springfield_aveva_pi
    maintenanceOrderTransformationExternalId: sap_maintenance_orders_springfield_s4hana
    operationTransformationExternalId: sap_operations_springfield_s4hana
    operationToMaintenanceOrderTransformationExternalId: sap_operation_to_maintenance_order_springfield_s4hana
    fileTransformationExternalId: files_metadata_springfield
    activityToAssetTransformationExternalId: activity_to_asset
    activityToEquipmentTransformationExternalId: activity_to_equipment
    activityToTimeSeriesTransformationExternalId: activity_to_timeseries
    timeSeriesToAssetTransformationExternalId: timeseries_to_asset
    timeSeriesToEquipmentTransformationExternalId: timeseries_to_equipment
    ingestionClientId: ${INGESTION_CLIENT_ID}
    ingestionClientSecret: ${INGESTION_CLIENT_SECRET}
    pandidContextualizationFunction: contextualization_p_and_id_annotater
    contextualization_connection_writer: contextualization_connection_writer
    schemaSpace2: cdf_cdm
    schemaSpace3: cdf_idm
    organization: YourOrg
    cdf_common:
      directRelationJob: ctx_files_direct_relation_write
      rawStateTable: diagramParsing

    bootcamp:
      CDF_PROJECT: <YOUR CDF PROJECT> # ex. cdf-bootcamp-01-test
      IDP_CLIENT_ID: ${IDP_CLIENT_ID} # replaced by .env
      IDP_CLIENT_SECRET: ${IDP_CLIENT_SECRET} # replaced by .env
      IDP_TENANT_ID: ${IDP_TENANT_ID} # replaced by .env
      # This is related to the cluster where the CDF project is hosted.
      CDF_URL: https://westeurope-1.cognitedata.com
      IDP_SCOPES: https://westeurope-1.cognitedata.com/.default
      IDP_TOKEN_URL: ${IDP_TOKEN_URL} # replaced by .env
      # Groups
      # OBJECT ID FOR TEST/PROD DATA PIPELINE OEE ENTRA GROUP
      data_pipeline_oee_source_id: <NotSet>
      # OBJECT ID FOR TEST/PROD ADMIN TK ENTRA GROUP
      readwrite_source_id: <NotSet>
      # OBJECT ID FOR TEST/PROD ADMIN TK ENTRA GROUP
      readonly_source_id: <NotSet>
      # OBJECT ID FOR TEST/PROD ICAPI EXTRACTORS ENTRA GROUP
      icapi_extractors_source_id: <NotSet>
      # Client Ids
      data_pipeline_oee_client_id: ${DATA_PIPELINE_OEE_CLIENT_ID} # replaced by .env
      data_pipeline_oee_client_secret: ${DATA_PIPELINE_OEE_CLIENT_SECRET} # replaced by .env
      icapi_extractors_client_id: ${ICAPI_EXTRACTORS_CLIENT_ID} # replaced by .env
      icapi_extractors_client_secret: ${ICAPI_EXTRACTORS_CLIENT_SECRET} # replaced by .env
      # Variables shared by modules
      icapi_ds_external_id: ds_icapi
      use_cases:
        oee:
          uc_oee_ds_external_id: ds_uc_oee

    common:
      cdf_apm_base:
        apm_datamodel_space: APM_SourceData

      cdf_auth_readwrite_all:
        readonly_source_id: 7bdcb20c-3e6a-400c-b9ef-cf835f64f05e
        readwrite_source_id: 684237e9-c1fd-4d3c-8c50-de9ea30ac16f

    industrial_tools:
      cdf_search:
        location: springfield
        locationName: Springfield
        instanceSpace: springfield_instances

      cdf_location_filter_asset_centric:
        ds_asset: ds_asset_location_filter
        root_asset: my_root_asset
        root_asset2: my_root_asset2
        ts_prefix: sensor

      cdf_location_filter_datamodel_based:
        instance_space1: my_instance_space1
        instance_space2: my_instance_space2

    infield:
      # The root asset external id should be
      # set to different values for each location,
      # but for demo purposes we are using the same value
      first_location: oid
      first_root_asset_external_id: WMT:VAL
      second_location: oid2
      second_root_asset_external_id: WMT:VAL
      cdf_infield_common:
        applicationsconfiguration_source_id: 7bdcb20c-3e6a-400c-b9ef-cf835f64f05e
        apm_config_instance_space: APM_Config

      cdf_infield_location:
        # This default_location points to the location created by the cdf_oid_example_data module.
        # When you create your own location by copying the cdf_oid_example_data module to
        # set up data sets and groups, the below needs to refer to the location to define.
        #
        module_version: '1'
        apm_datamodel_space: APM_SourceData
        apm_app_config_external_id: default-infield-config-minimal
        apm_config_instance_space: APM_Config
        # RAW databases to load workorders and other workorder data from
        # The below values point to the RAW database in the cdf_oid_example_data and should be
        # changed if you want to load workorders from another RAW database.
        source_asset: workmate
        source_workorder: workmate
        workorder_raw_db: workorder_oid_workmate
        # The table name in the raw_db database that has workorder data
        workorder_table_name: workorders
        # the root asset for this location, needs to be updated for each location
        # the following properties are required for
        # infield and must be updated for each location
        infield_location_checklist_admin_users_source_id: 684237e9-c1fd-4d3c-8c50-de9ea30ac16f
        infield_location_normal_users_source_id: 7bdcb20c-3e6a-400c-b9ef-cf835f64f05e
        infield_location_template_admin_users_source_id: 684237e9-c1fd-4d3c-8c50-de9ea30ac16f
        infield_location_viewer_users_source_id: 7bdcb20c-3e6a-400c-b9ef-cf835f64f05e

      cdf_infield_second_location:
        # This default_location points to the location created by the cdf_oid_example_data module.
        # When you create your own location by copying the cdf_oid_example_data module to
        # set up data sets and groups, the below needs to refer to the location to define.
        #
        module_version: '1'
        apm_datamodel_space: APM_SourceData
        apm_app_config_external_id: default-infield-config-minimal
        # RAW databases to load workorders and other workorder data from
        # The below values point to the RAW database in the cdf_oid_example_data and should be
        # changed if you want to load workorders from another RAW database.
        source_asset: workmate
        source_workorder: workmate
        workorder_raw_db: workorder_oid_workmate
        # The table name in the raw_db database that has workorder data
        workorder_table_name: workorders
        # the following properties are required for
        # infield and must be updated for each location
        infield_location_checklist_admin_users_source_id: 684237e9-c1fd-4d3c-8c50-de9ea30ac16f
        infield_location_normal_users_source_id: 7bdcb20c-3e6a-400c-b9ef-cf835f64f05e
        infield_location_template_admin_users_source_id: 684237e9-c1fd-4d3c-8c50-de9ea30ac16f
        infield_location_viewer_users_source_id: 7bdcb20c-3e6a-400c-b9ef-cf835f64f05e

    inrobot:
      first_root_asset_external_id: workmate
      first_location: workmate
      robot_1_dataset_ext_id: ds_robot_1
      cdf_inrobot_common:
        run_function_user_group_source_id: 684237e9-c1fd-4d3c-8c50-de9ea30ac16f
        run_function_client_id: ${RUN_FUNCTION_CLIENT_ID}
        run_function_secret: ${RUN_FUNCTION_CLIENT_SECRET}

      cdf_inrobot_location:
        inrobot_admin_first_location_source_id: 684237e9-c1fd-4d3c-8c50-de9ea30ac16f
        inrobot_users_first_location_source_id: 684237e9-c1fd-4d3c-8c50-de9ea30ac16f
        robot_1_first_location_source_id: 684237e9-c1fd-4d3c-8c50-de9ea30ac16f
        three_d_model_name: my_model
        three_d_type: my_type
        three_d_model_id: id_1
        three_d_revision_id: rev_1

    models:
      cdf_cdm_extension:
        organization: ToolkitMinimum
        schemaSpace: sp_enterprise_min_schema

      cdf_cdm_extension_full:
        organization: Toolkit
        schemaSpace: sp_enterprise_schema
