sourceName: Springfield AVEVA PI
sourceId: springfield_aveva_pi 
timeseriesTransformationExternalId: pi_timeseries_springfield_aveva_pi
dataset: ingestion
rawSourceDatabase: ingestion
instanceSpace: springfield_instances
organization: YourOrg
schemaSpace: sp_enterprise_process_industry

groupSourceId: <not set>
workflow: aveva_pi_population # can also contain location aveva_pi_springfield_population
workflowClientId: ${AVEVA_PI_SPRINGFIELD_CLIENT_ID}
workflowClientSecret: ${AVEVA_PI_SPRINGFIELD_CLIENT_SECRET}
