externalId: '{{ annotatorJob }}'
config:
  parameters:
    autoApprovalThreshold: 0.85
    autoRejectThreshold: 0.25
  sourceSystem:
    space: {{ annotationSpace }}
    externalId: {{ contextualizationId }}
  data:
    annotationSpace: '{{ annotationSpace }}'
    instanceSpaces:
      {{ instanceSpaces }}
    annotationJobs:
      - fileView:
          space: {{ schemaSpace }}
          externalId: CogniteFile
          version: v1
        entityViews:
          - space: {{ schemaSpace }}
            externalId: CogniteEquipment
            version: v1
            searchProperty: name
            type: diagrams.FileLink
          - space: {{ schemaSpace }}
            externalId: CogniteAsset
            version: v1
            searchProperty: name
            type: diagrams.AssetLink
          - space: {{ schemaSpace }}
            externalId: CogniteTimeSeries
            version: v1
            searchProperty: name
            type: diagrams.FileLink
