name: Smoke Tests

on:
  workflow_dispatch:
  schedule:
    # Run at 05:00 UTC every day
    - cron: '0 5 * * *'

permissions:
  contents: read

env:
  PYTHON_VERSION: 3.13

jobs:
  smoke-tests:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - CDF_CLUSTER: greenfield
            CDF_PROJECT: project-loader-dev
          - CDF_CLUSTER: bluefield
            CDF_PROJECT: toolkit-blue
          - CDF_CLUSTER: orangefield
            CDF_PROJECT: toolkit-orange
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6

      - name: Install uv and set the python version
        uses: astral-sh/setup-uv@cec208311dfd045dd5311c1add060b2062131d57 # v8.0.0
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Set up cache
        uses: actions/cache@27d5ce7f107fe9357f9df03efb73ab90386fccae # v5
        with:
          path: .venv
          key: venv-${{ hashFiles('pyproject.toml') }}-${{ hashFiles('uv.lock') }}

      - run: uv sync --all-extras

      - name: Run smoke tests
        env:
          CDF_CLUSTER: ${{ matrix.CDF_CLUSTER }}
          CDF_PROJECT: ${{ matrix.CDF_PROJECT }}
          IDP_CLIENT_ID: ${{ vars.IDP_CLIENT_ID }}
          IDP_CLIENT_SECRET: ${{ secrets.IDP_CLIENT_SECRET }}
          IDP_TOKEN_URL: ${{ vars.IDP_TOKEN_URL }}
        run: export PYTHONPATH=$PYTHONPATH:$(pwd); uv run pytest tests_smoke --json-report --json-report-file=smoke-report.json --tb=short
        continue-on-error: true

      - name: Check smoke test results and send Slack notification
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
          GITHUB_REPO_URL: ${{ github.server_url }}/${{ github.repository }}
        run: uv run python tests_smoke/check_smoke_results.py smoke-report.json
